#include <com/sun/star/uno/XInterface.idl>
 
module com { module github { module amourspirit { module extensions {
 
    interface XPy
    {
        sequence< sequence< any > > py( );
    };
 
}; }; }; };