#include <com/sun/star/uno/XInterface.idl>
 
module com { module github { module amourspirit { module extensions { module librepythonista {
 
interface XPy2: com::sun::star::uno::XInterface
{
    sequence< sequence< any > > pyc2( [in] long sheetIdx, [in] string cAddress, [in] any extras);
};
 
}; }; }; }; };