services:
  python_libre_pythonista_ext:
    env_file: ../.env
    network_mode: "bridge"
    # env_file: user.env
    build:
      context: ../../
      dockerfile: .devcontainer/lo_only/Dockerfile
      args:
        LO_VERSION: "version-7.6.7.2-r0"
        UV_VERSION: "0.5.5"
        CONFIG_DIR: /config
    # user: root
    container_name: lo_py_addon
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - PUID=0
      - PGID=0
      - CONFIG_DIR=/config
      - DEV_CONTAINER=1
      - WORK_DIR=/workspace/python_libre_pythonista_ext
    volumes:
      - type: bind
        source: ../../
        target: /workspace/python_libre_pythonista_ext
      - type: bind
        source: ../../Documents
        target: /config/Documents
      - type: bind
        source: ../../macro
        target: /config/.config/libreoffice/4/user/Scripts/python
      - type: volume
        source: app_lo_config
        target: /config
      - type: volume
        source: app_virtual_env
        target: /workspace/python_libre_pythonista_ext/.venv
    
    ports:
      - 3100:3000
      - 3101:3001
    restart: unless-stopped

volumes:
  app_virtual_env:
  app_lo_config: