help:
	@echo "Run make build to compile into 'build/sudoku' folder."

.PHONY: build help

build:
	oooscript compile --embed --config "$(PWD)/config.json" --embed-doc "$(PWD)/calc-sudoku.ods" --build-dir "build/sudoku"