UNO_DISPATCH_CODE_DEL = ".uno:libre_pythonista.calc.code.del"
UNO_DISPATCH_CODE_EDIT = ".uno:libre_pythonista.calc.code.edit"
UNO_DISPATCH_DF_STATE = ".uno:libre_pythonista.calc.code.df.state"
UNO_DISPATCH_DS_STATE = ".uno:libre_pythonista.calc.code.ds.state"
UNO_DISPATCH_PY_OBJ_STATE = ".uno:libre_pythonista.calc.py_obj.state"
UNO_DISPATCH_CELL_SELECT = ".uno:libre_pythonista.calc.cell.select"
